# """
# Django settings for project.

# Generated by 'django-admin startproject' using Django 5.0.7.

# For more information, see:
# https://docs.djangoproject.com/en/5.0/topics/settings/
# https://docs.djangoproject.com/en/5.0/ref/settings/
# """

# import os
# from pathlib import Path
# from dotenv import load_dotenv

# # Define the BASE_DIR
# BASE_DIR = Path(__file__).resolve().parent.parent
# import os
# from dotenv import load_dotenv

# load_dotenv()  # Load environment variables from .env file

# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

# print("DEBUG ALLOWED_HOSTS:", ALLOWED_HOSTS)  # Debugging

# # Read variables
# SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-default-key")
# DEBUG = os.getenv("DEBUG", "False").lower() in ["true", "1"]

# # Fix ALLOWED_HOSTS



# ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]
# print("ALLOWED_HOSTS:", ALLOWED_HOSTS)  # Debugging

# CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "https://ecommerce-neo9.onrender.com").split(",")

# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# from django.conf import settings
# print(settings.ALLOWED_HOSTS)



INSTALLED_APPS = [
    'paypal.standard.ipn',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this

]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config(default=os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3'))
# }



# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# # Static & Media Files
# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
# ALLOWED_HOSTS = []

# PAYPAL_RECEIVER_EMAIL = "busness@ggmail.com"
# PAYPAL_TEST = True 



# # busness@ggmail.com
# # busness@123




import os
from pathlib import Path
from dotenv import load_dotenv

# Define the BASE_DIR
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv()

ALLOWED_HOSTS = [
    'ecommercee-lkck.onrender.com',  # Add your Render domain
    '127.0.0.1',  # Allow local development
    'localhost'
]



# Load ALLOWED_HOSTS correctly
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]  # Remove extra spaces

# Debugging - Remove after verifying
print("DEBUG ALLOWED_HOSTS:", ALLOWED_HOSTS)  

# Read variables
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-default-key")
DEBUG = os.getenv("DEBUG", "False").lower() in ["true", "1"]

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://ecommercee-lkck.onrender.com'  # Add your Render domain for CSRF protection
]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



DATABASES ={
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SESSION_ENGINE = "django.contrib.sessions.backends.db"

SESSION_COOKIE_AGE = 86400 * 7  # 7 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# Email settings
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# PayPal settings
PAYPAL_RECEIVER_EMAIL = os.getenv("PAYPAL_RECEIVER_EMAIL", "busness@ggmail.com")
PAYPAL_TEST = True

# Static & Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

