# Generated by Django 5.1.4 on 2025-03-05 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=100)),
                ("productid", models.CharField(max_length=100)),
                ("qty", models.PositiveBigIntegerField()),
                ("totalprice", models.PositiveBigIntegerField()),
                ("orderid", models.CharField(default="0", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catname", models.CharField(max_length=80)),
                ("image", models.ImageField(upload_to="catimg")),
            ],
        ),
        migrations.CreateModel(
            name="UserRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("mob", models.TextField()),
                ("add", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("price", models.CharField(max_length=100)),
                ("STOCK", models.PositiveSmallIntegerField()),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add", models.TextField(default="Pending")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(default="Pending", max_length=50)),
                ("state", models.CharField(default="Pending", max_length=20)),
                ("pincode", models.CharField(default="Pending", max_length=6)),
                ("qty", models.CharField(default="Pending", max_length=6)),
                ("totalprice", models.CharField(default="Pending", max_length=50)),
                ("paytype", models.CharField(default="cash", max_length=20)),
                ("transactionid", models.CharField(default="Pending", max_length=50)),
                ("order_placed", models.DateTimeField(auto_now_add=True)),
                ("order_complited", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.userregister",
                    ),
                ),
            ],
        ),
    ]
