# Generated by Django 5.1.7 on 2025-03-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="transactionid",
        ),
    ]
