# Generated by Django 5.1.7 on 2025-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_order_transactionid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transactionid",
            field=models.CharField(
                blank=True, default="Pending", max_length=50, null=True
            ),
        ),
    ]
