# Generated by Django 5.1.7 on 2025-03-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_order_transactionid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
