# Generated by Django 4.1.2 on 2025-04-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_product_seller_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
